services:
  frontend:
    container_name: deeporigin-frontend
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    container_name: deeporigin-api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=sqlite:///app/database.sqlite
    volumes:
      - sqlite_data:/app/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  sqlite_data:
    driver: local
